# Generated by Django 3.0.3 on 2020-02-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='project_api.Project'),
        ),
    ]
